### ISSUE TITLE
Adding Multilanguage 

### ISSUE THREAD

**Issue by dipakja** [proxygo/O-fantasma-Detetive#1]
I just saw your website  and i don't understand the language.
So i thought , it needs multi-language feature that leads to everyone can read the text on your web-page.
I can add this feature using google translator.
You can assign me this issue.

**Comment by proxygo** [comment]
I thought your idea of ​​having a translator was cool, but I don't know how to implement it, if you want you can implement it. =)

**Comment by dipakja** [comment]
Ok, I will try.
